/* SONOFF PINS */
#define RELAY_PIN 12
#define LED_PIN 13
#define BUTTON_PIN 0

/* BLYNK VIRTUAL PINS */
#define BLYNK_TIMER_SHORT_VIRTUAL_PIN V1
#define BLYNK_TIMER_SHORT_VIRTUAL_BUTTON_PIN V2
#define BLYNK_TIMER_LONG_VIRTUAL_PIN V3
#define BLYNK_TIMER_LONG_VIRTUAL_BUTTON_PIN V4